name: SCA Go

on:
  push:
    branches:
      - "master"

jobs:
  perform-sca-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout go app
        uses: actions/checkout@v3
        with:
          repository: golang/example

      - uses: actions/setup-go@v3
        with:
          go-version: '1.15'

      - name: Contrast SCA Action
        uses: Markkuu/contrast-sca-action-test@main
        with:
          apiKey: ${{ secrets.CONTRAST_API_KEY }}
          orgId: ${{ secrets.CONTRAST_ORGANIZATION_ID }}
          authHeader: ${{ secrets.CONTRAST_AUTH_HEADER }}
          apiUrl: ${{ secrets.CONTRAST_API_URL }}
          filePath: .
