name: SCA Gradle

on:
  push:
    branches:
      - "master"

jobs:
  perform-sca-gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gradle app
        uses: actions/checkout@v3
        with:
          repository: gradle/native-platform

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Contrast SCA Action
        uses: Markkuu/contrast-sca-action-test@main
        with:
          apiKey: ${{ secrets.CONTRAST_API_KEY }}
          orgId: ${{ secrets.CONTRAST_ORGANIZATION_ID }}
          authHeader: ${{ secrets.CONTRAST_AUTH_HEADER }}
          apiUrl: ${{ secrets.CONTRAST_API_URL }}
          filePath: .
